num1 = float(input("Enter first number : "))
num2 = float(input("Enter second number : "))
print("sum : ", num1 + num2)
print("sub : ", num1 - num2)
print("mul : ", num1 * num2)
print("div : ", num1 / num2)
